# Generated by Django 5.1.5 on 2025-04-11 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_term', models.IntegerField(help_text='Loan term in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Calculation',
                'verbose_name_plural': 'Loan Calculations',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='EarlyPayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('start_month', models.IntegerField(help_text='Month to start extra payments (1-based)', validators=[django.core.validators.MinValueValidator(1)])),
                ('months_saved', models.IntegerField(default=0)),
                ('interest_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_loan.loancalculation')),
            ],
            options={
                'verbose_name': 'Early Payoff',
                'verbose_name_plural': 'Early Payoffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Comparison',
                'verbose_name_plural': 'Loan Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existing_debts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_recommended_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget_status', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Budget',
                'verbose_name_plural': 'Monthly Budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trade_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('doc_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loan_term', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('insurance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('extended_warranty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
