# Generated by Django 5.1.5 on 2025-04-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loancomparison',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='loancomparison',
            name='total_interest',
        ),
        migrations.AlterField(
            model_name='loancomparison',
            name='loan_term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loancomparison',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
