# Generated by Django 5.1.5 on 2025-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_loan', '0002_alter_loancomparison_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancomparison',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loancomparison',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loancomparison',
            name='vehicle_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
