global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Prometheus Scraping Its Own Metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. AI Vehicle Valuation Microservice (Port 5001)
  - job_name: 'ai_valuation_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']

  # 3. PDF Generator Microservice (Port 5002)
  - job_name: 'pdf_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5002']

  # 4. Django Web Gateway Application (Port 8000)
  - job_name: 'carloan_web_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
